---
version: '3'
services:
  fluentd:
    build: ./fluentd
    image: dinky98/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - front_net
      - back_net
    depends_on:
      - post_db

  elasticsearch:
    image: elasticsearch:7.4.0
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - front_net
      - back_net

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    networks:
      - front_net
      - back_net
    depends_on:
      - elasticsearch
      - fluentd

#networks:
#  docker_front_net:
#    external: true
#  docker_back_net:
#    external: true
