---
version: '3'
services:
  fluentd:
    image: dinky98/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - docker_front_net
      - docker_back_net
#    depends_on:
#      - post_db

  elasticsearch:
    image: elasticsearch:7.4.0
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - docker_front_net
      - docker_back_net

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      - docker_front_net
      - docker_back_net
    depends_on:
      - elasticsearch
      - fluentd

networks:
  docker_front_net:
    external: true
  docker_back_net:
    external: true
